#! /bin/bash

## configuration

show_git_branch="true"

## end of configuration

color_normal='\[\e[0m\]'

color_black='\[\e[0;31m\]'
color_red='\[\e[0;31m\]'
color_green='\[\e[0;32m\]'
color_blue='\[\e[0;34m\]'
color_purple='\[\e[0;35m\]'
color_cyan='\[\e[0;36m\]'

color_red_bold='\[\e[1;31m\]'
color_green_bold='\[\e[1;32m\]'
color_yellow_bold='\[\e[1;33m\]'
color_blue_bold='\[\e[1;34m\]'
color_purple_bold='\[\e[1;35m\]'
color_cyan_bold='\[\e[1;36m\]'

color_background='\[\e[103m\]'

PS1_PREFIX="${color_green_bold}\u@\h${color_normal}:${color_blue_bold}\w${color_normal}"

parse_git_branch() {

	if [ ${show_git_branch} != "true" ]; then
		git_branch=""
		return
	fi

    git_branch="$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/')"

    if [[ $(git status --porcelain 2> /dev/null | wc -l) -gt 0 ]]; then
    	git_branch="${color_red_bold}${git_branch}${color_normal}"    	
    elif [[ $(git log @{u}.. 2> /dev/null | wc -l) -gt 0 ]]; then    	
    	git_branch="${color_red_bold}${git_branch}${color_normal}"
    elif [[ $(git stash list 2> /dev/null | wc -l) -gt 0 ]]; then
    	git_branch="${color_yellow_bold}${git_branch}${color_normal}"
    else
    	git_branch="${color_green_bold}${git_branch}${color_normal}"
    fi
 

}


compose_prompt() {
     # PS1="${PS1_PREFIX}$(parse_git_branch)\$ "
     parse_git_branch
     # echo "branch: $git_branch"
     export PS1="${PS1_PREFIX}$git_branch\$ "
}

PROMPT_COMMAND=compose_prompt

# unset show_git_branch



# export PS1="${color_green_bold}\u@\h${color_normal}:${color_blue_bold}\w${color_normal} $(parse_git_branch)\$ "

# https://www.heise.de/select/ct/2020/16/2016314395986672871
# https://misc.flogisoft.com/bash/tip_colors_and_formatting
# https://unix.stackexchange.com/questions/105958/terminal-prompt-not-wrapping-correctly


# PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# https://askubuntu.com/questions/730754/how-do-i-show-the-git-branch-with-colours-in-bash-prompt
# https://stackoverflow.com/questions/3162444/git-count-files-in-the-staged-index
# https://stackoverflow.com/questions/5143795/how-can-i-check-in-a-bash-script-if-my-local-git-repository-has-changes
# https://github.com/nojhan/liquidprompt
# https://unix.stackexchange.com/questions/9605/how-can-i-detect-if-the-shell-is-controlled-from-ssh
